meta:
  # default sdk path
  sdk: ''
  # default toolchain path
  prefix: ''
  # default cc
  cc: clang
  # rootless
  rootless: True
  # optimization
  optimization: 0
  # warnings
  warnings: -Wall
  # entflag
  entflag: -S
  # entfile
  entfile: ''
  # deb compression (gzip, xz, bzip)
  compression: xz
  # architectures
  archs:
    - arm64
    - arm64e
  # platform
  platform: iphoneos
  # minVers
  minVers: 13.0

modules:
  # default module type
  defaultType: tweak
  # module types
  types:
    # tweak
    tweak:
      # filter
      filter:
        bundles:
          - com.apple.SpringBoard
      # use arc by default
      useArc: True
      # only compile changed by default
      onlyCompileChanged: True
      # frameworks
      frameworks:
        - CoreFoundation
        - Foundation
      # private frameworks
      private_frameworks: []
      # libraries
      libraries:
        - substrate
        - objc
    # tool
    tool:
      # use arc by default
      useArc: True
      # only compile changed by default
      onlyCompileChanged: False
      # frameworks
      frameworks:
        - CoreFoundation
        - Foundation
      # private frameworks
      private_frameworks: []
      # libraries
      libraries: []
