meta:
  # default sdk path
  sdk: ''
  # default toolchain path
  prefix: ''
  # default cc
  cc: clang
  # swift
  swiftc: swift
  # rootless
  rootless: True
  # deb compression (gzip, xz, bzip)
  compression: xz
  # architectures
  archs:
    - arm64
    - arm64e
  # platform
  platform: iphoneos
  # minVers
  minVers: 14.0

modules:
  # default module type
  defaultType: tweak
  # module types
  types:
    # tweak
    tweak:
      # cflags
      cflags: ''
      # swiftflags
      swiftflags: ''
      # optimization
      optimization: 0
      # warnings
      warnings: -Wall
      # entflag
      entflag: -S
      # entfile
      entfile: ''
      # filter
      filter:
        bundles:
          - com.apple.SpringBoard
      # use arc by default
      useArc: True
      # only compile changed by default
      onlyCompileChanged: True
      # bridging headers
      bridgingHeaders: []
      # frameworks
      frameworks:
        - CoreFoundation
        - Foundation
      # private frameworks
      private_frameworks: []
      # libraries
      libraries:
        - substrate
        - objc
    # tool
    tool:
      # cflags
      cflags: ''
      # swiftflags
      swiftflags: ''
      # optimization
      optimization: 0
      # warnings
      warnings: -Wall
      # entflag
      entflag: -S
      # entfile
      entfile: ''
      # use arc by default
      useArc: True
      # only compile changed by default
      onlyCompileChanged: False
      # bridging headers
      bridgingHeaders: []
      # frameworks
      frameworks:
        - CoreFoundation
        - Foundation
      # private frameworks
      private_frameworks: []
      # libraries
      libraries: []

submodules: []