name: Build package

env:
  zip-link: https://cdn.discordapp.com/attachments/883431899882749983/1066833307519688755/tweak.zip

on:
  release:
    types: [published]

  workflow_dispatch:
      
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode version (14.1)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.1.app

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
    
      - name: Install project
        run: pip install .
        
      - name: Get tweak zip
        run: |
            wget ${{ env.zip-link }}
            unzip tweak.zip
            which ar
            which gcc
            which clang
    
      - name: Build tweak
        run: cd tweak && luz