name: Build test package

env:
  zip-link: https://cdn.discordapp.com/attachments/820399697125965844/1078534203811057724/tweak.zip

on:
  release:
    types: [published]

  workflow_dispatch:
      
  push:
    paths:
    - luz/**.py
  pull_request:
    paths:
    - luz/**.py

jobs:
  build:
    name: Build
    runs-on: macos-12

    steps:
      - name: Select Xcode version (14.2)
        run: |
          sudo xcode-select --switch /Applications/Xcode_14.2.app
          
      - name: Install ldid
        run: |
          brew install ldid
          
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install project
        run: python -c "$(curl -fsSL https://raw.githubusercontent.com/LuzProject/luz/main/install.py)" -ns --ref="new-format"
        
      - name: Get tweak zip
        run: |
            wget ${{ env.zip-link }}
            unzip tweak.zip
    
      - name: Build tweak
        run: cd tweak && luz build
